/* Módulos del sistema: textos. Editar aquí. */
var M=[
/* ---------------- ACADÉMICO ---------------- */
{id:'admisiones',a:'academico',n:'Admisiones y matrícula',
 f:'Lleva a cada postulante desde la primera consulta hasta la matrícula, y reinscribe al colegio entero para la siguiente gestión.',
 p:'Postulaciones en papel o en formularios sueltos, cupos contados a mano y los mismos documentos pedidos dos veces.',
 s:['Postulación en línea con lista de documentos requeridos','Entrevistas y evaluaciones agendadas, con la decisión registrada','Control de cupos por curso y reserva de vacantes','Reinscripción masiva para la siguiente gestión'],
 u:['Secretaría','Dirección','Familias'],x:['crm','pensiones','portal','personas'],
 note:'Pregunta cuántas postulaciones reciben por gestión y cómo saben hoy cuántos cupos quedan. Muestra que el cupo se descuenta solo al matricular.',
 q:['¿Los padres pueden postular desde el celular?','Sí, desde la app o el portal, y suben los documentos ahí mismo.'],
 m:{t:'Admisiones 2027',u:'admisiones',b:'Nueva postulación',k:[['214','postulaciones'],['132','admitidos'],['18','cupos libres']],c:['Postulante','Curso','Documentos','Estado'],r:[['Rojas Arce, Valentina','Kínder A','4 de 5','a:Incompleta'],['Paz Limachi, Diego','1.º primaria','5 de 5','b:Entrevista'],['Salazar Vaca, Emilia','Kínder B','5 de 5','g:Admitida'],['Guzmán Ortiz, Tomás','4.º secundaria','5 de 5','g:Matriculado']]}},
{id:'curriculo',a:'academico',n:'Pensum y malla curricular',
 f:'Define qué se enseña en cada curso y cómo se relaciona cada materia del colegio con el plan oficial de SEDUCA.',
 p:'El plan propio del colegio y el oficial viven en documentos distintos, y la equivalencia se resuelve a mano cada vez que hay que reportar.',
 s:['Plan de estudios propio por nivel, grado y modalidad','Cada materia del colegio vinculada a su área oficial','Cargas horarias y versiones aprobadas por gestión','Es la base de horarios, notas y planificación'],
 u:['Coordinación','Dirección'],x:['notas','horarios','docente'],
 note:'Este módulo es el que hace posible la nota SEDUCA automática: el colegio enseña con su malla y el sistema sabe a qué área oficial corresponde cada materia.',
 m:{t:'Malla 3.º de secundaria',u:'curriculo/secundaria/3',b:'Nueva versión',k:[['14','materias'],['40','horas semanales'],['v3','versión vigente']],c:['Materia del colegio','Área SEDUCA','Horas','Estado'],r:[['Matemática','Matemática','6','g:Vigente'],['Robótica','Técnica tecnológica','2','g:Vigente'],['Inglés avanzado','Lengua extranjera','5','g:Vigente'],['Filosofía','Cosmovisiones y filosofía','2','a:Por aprobar']]}},
{id:'horarios',a:'academico',n:'Horarios y asignación docente',
 f:'Arma el horario de cada paralelo y asigna docentes y aulas sin choques.',
 p:'Horarios en Excel que se rompen cuando cambia un docente, y choques de aula que se descubren el primer día de clases.',
 s:['Horarios por curso, paralelo, grupo y subgrupo','Asignación docente según carga y disponibilidad','Aviso de choques de docente, aula o bloque','Cada cambio queda publicado y registrado'],
 u:['Coordinación','Docentes','Dirección'],x:['curriculo','asistencia','personal','reservas'],
 note:'Muestra que la lista de asistencia del docente sale del horario publicado: si el horario está bien, pasar lista es un clic.',
 m:{t:'Horario 3.º de secundaria B',u:'horarios/3b',b:'Publicar',k:[['38','bloques'],['12','docentes'],['0','choques']],c:['Bloque','Lunes','Martes','Estado'],r:[['08:00','Matemática, Quispe','Lenguaje, Mamani','g:OK'],['08:45','Física, Torrez','Matemática, Quispe','g:OK'],['10:15','Inglés, Brown','Química, Arce','a:Aula compartida'],['11:00','Ed. Física, Vaca','Historia, Flores','g:OK']]}},
{id:'asistencia',a:'academico',n:'Asistencia',
 f:'Registra quién vino, quién faltó y quién llegó tarde, y avisa a la familia el mismo día.',
 p:'Listas en papel que se pasan a una planilla días después, y familias que se enteran de las faltas al final del trimestre.',
 s:['Lista del curso lista desde el horario del día','Tardanzas, permisos y justificaciones con respaldo','Aviso automático a la familia cuando el estudiante falta','Reportes por estudiante, curso y sede'],
 u:['Docentes','Secretaría','Familias'],x:['horarios','portal','riesgo','bienestar'],
 note:'Pregunta: “¿cuándo se entera hoy una familia de que su hijo faltó?”. Con PeopleCole, el mismo día y en su celular.',
 m:{t:'Asistencia de hoy, 3.º B',u:'asistencia/hoy',b:'Guardar lista',k:[['26','presentes'],['2','faltas'],['1','tardanza']],c:['Estudiante','Llegada','Justificación','Estado'],r:[['Choque Rivera, Mateo','—','Sin justificar','r:Falta'],['Vargas Loza, Sofía','08:12','—','a:Tardanza'],['Mamani Quispe, Ana','07:55','—','g:Presente'],['Rojas Paz, Joaquín','—','Certificado médico','b:Justificada']]}},
{id:'notas',a:'academico',n:'Notas, boletines y promoción',
 f:'El docente califica una sola vez y el sistema calcula la nota del colegio, la nota SEDUCA y el boletín.',
 p:'Notas en planillas por docente, doble carga para SEDUCA y boletines armados a mano en cada cierre de trimestre.',
 s:['Libro de notas por materia, trimestre y paralelo','Nota por dimensiones (ser, saber, hacer, decidir) y nota SEDUCA calculada','Cierre de trimestre controlado; reabrir requiere aprobación','Boletines publicados en la app y promoción de fin de gestión'],
 u:['Docentes','Coordinación','Familias','Estudiantes'],x:['curriculo','portal','riesgo','tramites'],
 note:'Es el módulo estrella para un director. Pregunta cuántos días les toma hoy cerrar un trimestre y cuántas veces se cargan las mismas notas.',
 q:['¿Se puede cambiar una nota después del cierre?','Sí, con una solicitud de reapertura aprobada. Queda registrado quién la cambió, cuándo y por qué.'],
 m:{t:'Matemática 3.º B, 2.º trimestre',u:'notas/3b/matematica',b:'Cerrar trimestre',k:[['28','estudiantes'],['71','promedio'],['3','bajo el mínimo']],c:['Estudiante','Nota colegio','Nota SEDUCA','Estado'],r:[['Mamani Quispe, Ana','88','76','g:Aprobado'],['Choque Rivera, Mateo','49','42','r:Reprobado'],['Flores Arce, Lucía','94','82','g:Aprobado'],['Vargas Loza, Sofía','61','53','a:Recuperación']]}},
{id:'docente',a:'academico',n:'Planificación docente',
 f:'El docente planifica sus clases y el colegio ve cuánto del programa se avanzó en cada curso.',
 p:'Planificaciones en Word que nadie revisa y un avance curricular que se conoce recién al final del año.',
 s:['Planes de clase por materia, grupo y periodo','Registro de lo que se dio en cada clase','Avance del programa en porcentaje','Evidencias de clase adjuntas'],
 u:['Docentes','Coordinación'],x:['curriculo','horarios','notas'],
 note:'La pregunta para el director: “¿cómo sabe hoy si un curso va atrasado en el programa?”. Aquí lo ve en un número.',
 m:{t:'Avance curricular, secundaria',u:'planificacion/avance',b:'Ver detalle',k:[['78%','avance promedio'],['142','planes entregados'],['6','cursos atrasados']],c:['Docente','Materia','Avance','Estado'],r:[['Quispe, Luis','Matemática 3.º','82%','g:Al día'],['Mamani, Rosa','Lenguaje 3.º','64%','a:Atrasado'],['Torrez, Jorge','Física 4.º','79%','g:Al día'],['Arce, Paola','Química 5.º','71%','g:Al día']]}},
{id:'calendario',a:'academico',n:'Calendario institucional',
 f:'Una sola fuente de fechas: gestión, trimestres, feriados, jornadas y plazos.',
 p:'Cada área maneja su propio calendario y los plazos de notas o matrícula se avisan por WhatsApp.',
 s:['Gestión y trimestres con fechas de apertura y cierre','Feriados, recesos y suspensiones por sede','Plazos de matrícula, notas y RUDE','Todos los módulos respetan estas fechas'],
 u:['Dirección','Coordinación','Secretaría'],x:['notas','admisiones','asistencia'],
 note:'Cuando se cierra el plazo de notas, el sistema no deja cargar más sin autorización. Eso ordena los cierres sin perseguir a nadie.',
 m:{t:'Calendario, gestión 2026',u:'calendario',b:'Nuevo evento',k:[['3','trimestres'],['182','días hábiles'],['4','plazos abiertos']],c:['Evento','Desde','Hasta','Estado'],r:[['Carga de notas 2.º trimestre','01/09','20/09','g:Abierto'],['Actualización RUDE','15/09','30/09','g:Abierto'],['Descanso pedagógico','28/09','02/10','b:Programado'],['Reinscripción 2027','01/10','31/10','a:Próximo']]}},

/* ---------------- ECONÓMICO ---------------- */
{id:'pensiones',a:'economico',n:'Pensiones y aranceles',
 f:'Genera lo que cada familia debe pagar y mantiene su estado de cuenta siempre al día.',
 p:'Cargos armados en Excel, becas descontadas a mano y estados de cuenta que hay que preparar cada vez que un padre pregunta.',
 s:['Aranceles por gestión, sede, nivel y concepto','Cargos del mes para todo el colegio en una sola acción','Planes de cuotas visibles para la familia, incluso atrasados','Estado de cuenta por familia y por estudiante'],
 u:['Administración','Familias'],x:['becas','pagos','cobranza','portal'],
 note:'Muestra el botón “generar cargos del mes”: un clic para todo el colegio, con las becas ya descontadas.',
 q:['¿Se pueden cobrar otros conceptos, como uniformes o salidas?','Sí, cualquier concepto: matrícula, pensión, materiales, eventos o servicios.'],
 m:{t:'Cuentas por cobrar, septiembre',u:'cobranza/cuentas',b:'Generar cargos de octubre',k:[['Bs 412.300','facturado'],['Bs 376.520','cobrado'],['91,4%','cobranza']],c:['Familia','Concepto','Monto','Estado'],r:[['Choque Rivera','Pensión septiembre','Bs 850','a:En plan'],['Mamani Quispe','Pensión septiembre','Bs 722','g:Pagado'],['Rojas Paz','Pensión agosto','Bs 850','r:Mora 47 días'],['Vargas Loza','Pensión septiembre','Bs 425','g:Pagado']]}},
{id:'becas',a:'economico',n:'Becas, descuentos y convenios',
 f:'Administra todos los beneficios económicos con reglas claras y aprobación.',
 p:'Becas acordadas de palabra, descuentos aplicados a mano, y nadie sabe cuánto le cuestan al colegio en total.',
 s:['Programas de becas y descuentos con vigencia','Descuento por hermanos y convenios con empresas','Solicitud con respaldo y aprobación por comité','Se aplican solos en las cuotas y el costo total queda visible'],
 u:['Administración','Dirección','Familias'],x:['pensiones','aprobaciones','reglas'],
 note:'A los directores les interesa saber cuánto dinero representan las becas. Aquí lo ven en un número, por mes.',
 m:{t:'Beneficios vigentes',u:'becas',b:'Nueva solicitud',k:[['186','beneficiarios'],['Bs 48.200','por mes'],['4','solicitudes nuevas']],c:['Beneficio','Tipo','Estudiantes','Estado'],r:[['Hermanos 15%','Descuento','64','g:Vigente'],['Beca excelencia 50%','Beca','22','g:Vigente'],['Convenio Empresa Andina','Convenio','31','g:Vigente'],['Beca solidaria','Beca','4','a:Por aprobar']]}},
{id:'cobranza',a:'economico',n:'Mora y cobranza',
 f:'Organiza el seguimiento de las familias con deuda, sin perder la relación con ellas.',
 p:'La cobranza depende de que alguien revise el cuaderno y llame; no queda registro de lo que se habló ni de lo que se prometió.',
 s:['Mora por antigüedad y por sede','Historial de cada contacto con la familia','Compromisos de pago con cuotas y firma','Recordatorios automáticos antes y después del vencimiento'],
 u:['Administración','Dirección'],x:['pensiones','pagos','comunicacion','documentos'],
 note:'Pregunta cuánto es la mora hoy y quién la sigue. Muestra que el compromiso de pago se firma desde la app.',
 m:{t:'Cartera en mora',u:'cobranza/mora',b:'Enviar recordatorios',k:[['Bs 21.850','más de 30 días'],['21','familias'],['9','compromisos']],c:['Familia','Deuda','Antigüedad','Estado'],r:[['Rojas Paz','Bs 850','47 días','a:Contactado'],['Salinas Cruz','Bs 1.700','75 días','b:Compromiso'],['Ortiz Mendoza','Bs 2.550','92 días','r:Escalado'],['Aliaga Soto','Bs 850','33 días','a:Recordatorio']]}},
{id:'pagos',a:'economico',n:'Pagos por QR y en línea',
 f:'Las familias pagan desde el celular y el pago se aplica solo a la cuota correcta.',
 p:'Padres que mandan la foto del comprobante por WhatsApp y alguien que busca cada pago en el extracto del banco.',
 s:['QR bancario, tarjeta, transferencia y pago en caja','Confirmación automática y aplicación a la cuota','Devoluciones y reversos controlados','Control de pagos duplicados o sospechosos'],
 u:['Familias','Administración'],x:['pensiones','tesoreria','portal','tienda'],
 note:'Es el momento de sacar el celular: la familia paga con QR y, en la pantalla del colegio, la cuota pasa a “pagado” sola.',
 q:['¿Con qué bancos funciona?','Con las pasarelas y bancos que el colegio habilite; se configura por proveedor.'],
 m:{t:'Pagos recibidos hoy',u:'pagos/hoy',b:'Exportar',k:[['46','pagos QR'],['Bs 38.900','recibido'],['0','sin aplicar']],c:['Hora','Familia','Canal','Estado'],r:[['09:14','Mamani Quispe','QR','g:Aplicado'],['09:31','Vargas Loza','Transferencia','g:Aplicado'],['10:02','Guzmán Ortiz','Tarjeta','g:Aplicado'],['10:20','Paz Limachi','QR','b:Confirmando']]}},
{id:'tesoreria',a:'economico',n:'Caja y bancos',
 f:'Controla la caja diaria, los depósitos y la conciliación con el banco.',
 p:'Arqueos en papel, diferencias que nadie explica y extractos revisados línea por línea.',
 s:['Cajas por sede con apertura, arqueo y cierre','Recibos, anulaciones y diferencias registradas','Depósitos con respaldo','Conciliación bancaria contra los pagos del sistema'],
 u:['Administración'],x:['pagos','pensiones','contable'],
 note:'Para el promotor: cada boliviano que entra tiene recibo, cajero responsable y cierre del día.',
 m:{t:'Caja, sede Calacoto',u:'caja/calacoto',b:'Cerrar caja',k:[['Bs 18.420','recaudado hoy'],['64','recibos'],['Bs 0','diferencia']],c:['Sesión','Cajero','Monto','Estado'],r:[['Caja 1, mañana','R. Condori','Bs 11.250','g:Cerrada'],['Caja 2, mañana','M. Ríos','Bs 7.170','g:Cerrada'],['Caja 1, tarde','R. Condori','Bs 2.100','b:Abierta'],['Depósito 25/09','—','Bs 18.420','g:Conciliado']]}},
{id:'compras',a:'economico',n:'Compras y proveedores',
 f:'Del pedido interno a la orden de compra y la recepción, con proveedores habilitados.',
 p:'Compras por WhatsApp, cotizaciones que nadie compara y facturas que llegan sin saber quién pidió qué.',
 s:['Pedidos internos con aprobación','Cotizaciones y cuadro comparativo','Orden de compra y recepción parcial o total','Proveedores habilitados, contratos y evaluación'],
 u:['Administración','Dirección'],x:['inventario','cxp','contable','aprobaciones'],
 note:'Mensaje clave: ningún gasto sin pedido, aprobación y recepción. El director sabe en qué se gasta cada peso.',
 m:{t:'Compras en curso',u:'compras',b:'Nuevo pedido',k:[['12','pedidos'],['5','órdenes abiertas'],['Bs 34.600','comprometido']],c:['Pedido','Área','Monto','Estado'],r:[['Material de laboratorio','Ciencias','Bs 6.800','b:Cotizando'],['Tóner para impresoras','Secretaría','Bs 1.950','g:Recibido'],['Pintura de aulas','Mantenimiento','Bs 12.400','a:Por aprobar'],['Balones y redes','Ed. Física','Bs 2.300','b:Orden emitida']]}},
{id:'cxp',a:'economico',n:'Cuentas por pagar',
 f:'Ordena lo que el colegio debe a sus proveedores y cuándo toca pagar.',
 p:'Pagos a proveedores que se olvidan o se duplican, sin relación con la compra que los originó.',
 s:['Cada deuda vinculada a su compra o contrato','Calendario de pagos y vencimientos','Aprobación antes de pagar','Envío a contabilidad'],
 u:['Administración'],x:['compras','tesoreria','contable'],
 note:'Complementa compras: cada pago tiene su respaldo y su aprobación.',
 m:{t:'Por pagar',u:'cuentas-por-pagar',b:'Programar pagos',k:[['Bs 58.300','pendiente'],['7','vencen esta semana'],['0','sin respaldo']],c:['Proveedor','Documento','Vence','Estado'],r:[['Distribuidora Illimani','Factura 1482','30/09','a:Por aprobar'],['Servicios Andes','Contrato limpieza','05/10','b:Programado'],['Librería Central','Factura 889','28/09','g:Aprobado'],['Imprenta Sur','Factura 212','15/09','g:Pagado']]}},
{id:'cajachica',a:'economico',n:'Caja chica',
 f:'Controla los gastos menores con responsable, comprobante y rendición.',
 p:'Gastos pequeños sin respaldo y rendiciones armadas con una bolsa de recibos sueltos.',
 s:['Fondos por responsable y sede','Gasto registrado con foto del comprobante','Rendición, revisión y reposición','Reembolsos al personal'],
 u:['Administración','Personal'],x:['tesoreria','contable'],
 note:'Módulo pequeño, pero los administradores lo valoran mucho: se acaba la bolsa de recibos.',
 m:{t:'Fondos de caja chica',u:'caja-chica',b:'Registrar gasto',k:[['4','fondos activos'],['Bs 3.200','disponible'],['2','por rendir']],c:['Responsable','Fondo','Saldo','Estado'],r:[['Secretaría Calacoto','Bs 1.000','Bs 420','a:Por rendir'],['Mantenimiento','Bs 1.500','Bs 1.180','g:Al día'],['Dirección','Bs 1.000','Bs 900','g:Al día'],['Sede Miraflores','Bs 1.000','Bs 700','b:En revisión']]}},
{id:'contable',a:'economico',n:'Integración contable',
 f:'Envía la información económica al sistema contable y de facturación que el colegio ya usa.',
 p:'El contador vuelve a digitar lo que caja ya registró, y los cierres de mes no cuadran.',
 s:['Cada cobro, pago y compra genera su registro contable','Plantillas contables configurables','Sincronización con el sistema contable y de facturación del colegio','Referencias fiscales con NIT'],
 u:['Administración'],x:['tesoreria','pensiones','compras','cxp'],
 note:'Aclara que PeopleCole no reemplaza al contador ni al sistema de facturación: los alimenta sin doble digitación.',
 q:['¿PeopleCole emite la factura?','La factura se emite en el sistema de facturación del colegio; PeopleCole le envía los datos y guarda la referencia.'],
 m:{t:'Sincronización contable',u:'contabilidad',b:'Sincronizar',k:[['1.248','registros del mes'],['1.241','enviados'],['7','por revisar']],c:['Origen','Descripción','Monto','Estado'],r:[['Cobranza','Pensiones 25/09','Bs 18.420','g:Enviado'],['Compras','Orden 2026-118','Bs 6.800','g:Enviado'],['Caja chica','Rendición Secretaría','Bs 580','a:Por revisar'],['Becas','Descuentos septiembre','Bs 48.200','g:Enviado']]}},

/* ---------------- VIDA ESCOLAR ---------------- */
{id:'convivencia',a:'vida',n:'Convivencia y disciplina',
 f:'Registra incidentes, medidas y acuerdos, con un expediente claro para cada caso.',
 p:'Incidentes anotados en un cuaderno, medidas sin respaldo y familias que reclaman que nunca se les informó.',
 s:['Incidentes con uno o varios estudiantes involucrados','Clasificación por gravedad','Medidas, acuerdos y seguimiento','Comunicación a la familia registrada y decisión de dirección'],
 u:['Dirección','Orientación','Docentes','Familias'],x:['bienestar','comunicacion','portal'],
 note:'El argumento para el director es respaldo: si una familia reclama, el expediente muestra qué pasó, qué se decidió y cuándo se le informó.',
 m:{t:'Casos de convivencia',u:'convivencia',b:'Registrar incidente',k:[['9','abiertos'],['3','esperan decisión'],['2','graves']],c:['Incidente','Involucrados','Gravedad','Estado'],r:[['Discusión verbal en recreo','2 estudiantes','Leve','g:Cerrado'],['Falta de respeto a docente','1 estudiante','Moderada','a:Seguimiento'],['Agresión física','3 estudiantes','Grave','r:En dirección'],['Uso de celular en examen','1 estudiante','Leve','b:Acuerdo']]}},
{id:'bienestar',a:'vida',n:'Orientación y bienestar',
 f:'Junta las señales de cada estudiante y organiza el acompañamiento de orientación, psicología y psicopedagogía.',
 p:'Cada docente ve un pedazo del problema y nadie ve el cuadro completo hasta que es tarde.',
 s:['Un expediente por estudiante con alertas de aula e incidentes','Planes de acompañamiento con sesiones y responsables','Familia notificada y acuerdos registrados','Notas privadas que solo ve cada especialista'],
 u:['Orientación','Docentes','Dirección','Familias'],x:['asistencia','notas','convivencia','riesgo'],
 note:'Cuenta un caso: un estudiante falta, baja sus notas y los docentes lo notan distraído. Aquí se ve todo junto y orientación actúa antes del boletín.',
 m:{t:'Casos de acompañamiento',u:'orientacion/casos',b:'Nuevo plan',k:[['12','casos abiertos'],['5','sugerencias nuevas'],['3','familias por citar']],c:['Estudiante','Motivo','Responsable','Estado'],r:[['Choque Rivera, Mateo','Faltas y notas bajas','Orientación','r:Nuevo'],['Mamani Quispe, Ana','Adaptación','Psicología','b:En curso'],['Quispe Flores, Iván','Seguimiento','Psicopedagogía','a:Observación'],['Rojas Paz, Joaquín','Rendimiento','Tutor de curso','g:Cerrado']]}},
{id:'salud',a:'vida',n:'Enfermería y salud escolar',
 f:'Fichas médicas, alergias, medicación y atenciones de enfermería, en un lugar seguro.',
 p:'Fichas médicas en carpetas, y alergias que el comedor o el profesor de la salida no conocen.',
 s:['Ficha médica y alergias con acceso restringido','Medicación autorizada por la familia y registrada','Atenciones de enfermería con aviso a la familia','Protocolo de emergencias'],
 u:['Personal','Familias'],x:['alimentacion','extracurriculares','seguridad'],
 note:'Resalta la privacidad: el comedor sabe que un niño no puede comer maní, pero no ve su ficha médica completa.',
 m:{t:'Enfermería hoy',u:'enfermeria',b:'Nueva atención',k:[['14','atenciones'],['6','medicaciones'],['0','emergencias']],c:['Estudiante','Motivo','Hora','Estado'],r:[['Salazar Vaca, Emilia','Dolor de cabeza','09:40','g:Volvió a clase'],['Paz Limachi, Diego','Medicación autorizada','10:00','g:Administrada'],['Guzmán Ortiz, Tomás','Golpe en recreo','10:35','a:Familia avisada'],['Aliaga Soto, Mía','Fiebre','11:10','b:Retiro por familia']]}},
{id:'extracurriculares',a:'vida',n:'Actividades extracurriculares',
 f:'Clubes, deportes y talleres con inscripción, cupos, autorización y asistencia.',
 p:'Inscripciones en hojas, cupos sobrepasados y autorizaciones que se pierden.',
 s:['Oferta con cupo, horario e instructor','Inscripción desde la app con lista de espera','Autorización de la familia y cobro si corresponde','Asistencia y seguimiento por actividad'],
 u:['Coordinación','Familias','Estudiantes'],x:['portal','pensiones','salud'],
 note:'Buen ejemplo de cómo todo se conecta: inscripción en la app, cobro en el estado de cuenta y autorización firmada, sin papeles.',
 m:{t:'Actividades extracurriculares',u:'extracurriculares',b:'Nueva actividad',k:[['18','actividades'],['412','inscritos'],['27','en espera']],c:['Actividad','Cupo','Inscritos','Estado'],r:[['Fútbol sub-12','24','24','a:Lleno'],['Robótica','16','12','g:Abierta'],['Coro','30','21','g:Abierta'],['Ajedrez','20','20','a:Lleno']]}},
{id:'biblioteca',a:'vida',n:'Biblioteca',
 f:'Catálogo, préstamos, reservas y devoluciones de la biblioteca.',
 p:'Préstamos anotados en un cuaderno y libros que no vuelven.',
 s:['Catálogo con ejemplares y código de barras','Préstamos, renovaciones y reservas','Avisos de devolución','Inventario de la colección'],
 u:['Personal','Estudiantes','Docentes'],x:['inventario','portal'],
 note:'Módulo sencillo. Úsalo como ejemplo de que el sistema cubre hasta los detalles del día a día.',
 m:{t:'Biblioteca',u:'biblioteca',b:'Nuevo préstamo',k:[['8.420','ejemplares'],['312','préstamos activos'],['18','atrasados']],c:['Título','Lector','Devuelve','Estado'],r:[['Cien años de soledad','Flores Arce, Lucía','30/09','g:Prestado'],['Álgebra','Rojas Paz, Joaquín','20/09','r:Atrasado'],['Atlas de Bolivia','Prof. Mamani','05/10','g:Prestado'],['El principito','Salazar Vaca, Emilia','—','b:Reservado']]}},
{id:'alimentacion',a:'vida',n:'Comedor y alimentación',
 f:'Menús, planes de alimentación, consumos y restricciones alimentarias.',
 p:'El personal del comedor no sabe qué estudiante es alérgico, y los consumos se cobran con listas.',
 s:['Menús publicados con alérgenos','Planes de alimentación y su cobro','Registro de consumo por estudiante','Alerta automática ante restricciones'],
 u:['Personal','Familias'],x:['salud','pensiones','portal'],
 note:'Muestra la alerta: el sistema avisa si el menú del día tiene algo que ese estudiante no puede comer.',
 m:{t:'Comedor, almuerzo de hoy',u:'comedor',b:'Publicar menú',k:[['486','raciones'],['23','con restricción'],['2','alertas']],c:['Estudiante','Plan','Restricción','Estado'],r:[['Paz Limachi, Diego','Mensual','Maní','r:Alerta de menú'],['Mamani Quispe, Ana','Mensual','—','g:Servido'],['Guzmán Ortiz, Tomás','Diario','Lactosa','g:Menú alternativo'],['Flores Arce, Lucía','Mensual','—','b:Pendiente']]}},

/* ---------------- CAMPUS ---------------- */
{id:'transporte',a:'campus',n:'Transporte escolar',
 f:'Rutas, paradas, vehículos y el registro de subida y bajada de cada estudiante.',
 p:'Listas de transporte en papel y familias que llaman para saber si su hijo subió al bus.',
 s:['Rutas y paradas por sede y turno','Estudiantes asignados con autorización familiar','Registro de subida y bajada','Incidentes y avisos a la familia'],
 u:['Personal','Familias'],x:['seguridad','portal','pensiones'],
 note:'Pregunta a quién llama hoy un padre para saber si su hijo subió al bus. Con PeopleCole lo ve en la app.',
 m:{t:'Transporte, salida de la tarde',u:'transporte',b:'Ver mapa',k:[['8','rutas'],['214','estudiantes'],['1','incidente']],c:['Ruta','Conductor','Pasajeros','Estado'],r:[['Ruta 1 Sopocachi','J. Mamani','28 de 30','g:En camino'],['Ruta 2 Obrajes','L. Choque','26 de 26','g:Completada'],['Ruta 3 Achumani','P. Quispe','22 de 24','a:Retraso 10 min'],['Ruta 4 Irpavi','R. Vargas','30 de 30','b:Por salir']]}},
{id:'seguridad',a:'campus',n:'Portería y retiro de estudiantes',
 f:'Controla quién entra al colegio y quién puede retirar a cada estudiante.',
 p:'Visitantes anotados en un cuaderno en portería y retiros que dependen de que el guardia conozca al padre.',
 s:['Registro de visitantes con pase QR','Personas autorizadas para retirar a cada estudiante','Validación en portería y registro de cada salida','Incidentes y protocolo de emergencias'],
 u:['Personal','Familias','Dirección'],x:['salud','transporte','portal'],
 note:'Es un tema que preocupa mucho a los padres. Úsalo como argumento que el colegio puede mostrar a sus propias familias.',
 m:{t:'Portería principal',u:'porteria',b:'Registrar visita',k:[['37','visitantes hoy'],['112','retiros'],['1','rechazado']],c:['Persona','Motivo','Hora','Estado'],r:[['Carla Rivera','Retiro de Mateo','12:40','g:Autorizada'],['Técnico de internet','Mantenimiento','10:15','g:Con pase'],['Persona no registrada','Retiro de Sofía','12:52','r:Rechazado'],['Jorge Paz','Reunión con dirección','11:00','b:En el colegio']]}},
{id:'inventario',a:'campus',n:'Inventario y almacenes',
 f:'Materiales y suministros con stock, movimientos y entregas.',
 p:'No se sabe cuánto material queda hasta que se acaba.',
 s:['Artículos con stock mínimo','Entradas, salidas y traspasos entre sedes','Entregas a cada área con responsable','Conteos físicos'],
 u:['Administración','Personal'],x:['compras','activos','tienda'],
 note:'Se conecta con compras: cuando el stock baja del mínimo, aparece la necesidad de compra.',
 m:{t:'Almacén central',u:'inventario',b:'Registrar entrega',k:[['612','artículos'],['14','bajo el mínimo'],['Bs 86.400','valor']],c:['Artículo','Stock','Mínimo','Estado'],r:[['Hojas bond carta','42 paquetes','50','a:Bajo mínimo'],['Marcadores de pizarra','180','100','g:OK'],['Tóner','3','5','r:Reponer'],['Papel higiénico','240','120','g:OK']]}},
{id:'activos',a:'campus',n:'Activos y equipamiento',
 f:'Qué equipos tiene el colegio, dónde están y quién responde por ellos.',
 p:'Proyectores y computadoras que nadie sabe en qué aula están ni cuándo se les hizo mantenimiento.',
 s:['Código único por equipo, con ubicación','Responsable asignado y traslados aprobados','Mantenimiento y garantías','Bajas con respaldo'],
 u:['Administración','Personal'],x:['mantenimiento','inventario','reservas'],
 note:'Para el promotor es el patrimonio del colegio, controlado y con responsable.',
 m:{t:'Activos, sede Calacoto',u:'activos',b:'Nuevo activo',k:[['1.126','activos'],['18','en mantenimiento'],['4','por dar de baja']],c:['Activo','Ubicación','Responsable','Estado'],r:[['Proyector #0412','Aula 3.º B','Prof. Quispe','g:Operativo'],['Laptop #0877','Laboratorio','Lic. Arce','a:Mantenimiento'],['Microscopio #0120','Laboratorio','Lic. Arce','g:Operativo'],['Impresora #0033','Secretaría','R. Condori','r:Baja']]}},
{id:'reservas',a:'campus',n:'Reserva de aulas y laboratorios',
 f:'Los docentes reservan espacios y equipos sin choques.',
 p:'El laboratorio se reserva en una hoja pegada en la puerta y dos cursos llegan a la misma hora.',
 s:['Espacios y equipos reservables','Calendario de disponibilidad','Aprobación cuando corresponde','Registro de uso y devolución'],
 u:['Docentes','Personal'],x:['horarios','activos'],
 note:'Ejemplo corto y fácil de mostrar.',
 m:{t:'Reservas de esta semana',u:'reservas',b:'Reservar',k:[['46','reservas'],['3','laboratorios'],['0','choques']],c:['Espacio','Solicitante','Horario','Estado'],r:[['Laboratorio de química','Lic. Arce','Mar 10:15','g:Confirmada'],['Auditorio','Dirección','Vie 15:00','g:Confirmada'],['Sala de computación','Prof. Torrez','Mié 08:45','a:Por aprobar'],['Carro de laptops','Prof. Mamani','Jue 11:00','g:Confirmada']]}},
{id:'mantenimiento',a:'campus',n:'Mantenimiento',
 f:'Pedidos de mantenimiento con prioridad, responsable y plazo.',
 p:'Arreglos pedidos de palabra que se olvidan, sin saber cuándo se resolvieron.',
 s:['Pedidos desde cualquier área','Prioridad y plazo según urgencia','Órdenes de trabajo internas o con proveedor','Mantenimiento preventivo programado'],
 u:['Personal','Administración','Docentes'],x:['activos','compras','inventario'],
 note:'Pregunta cuánto tarda hoy en arreglarse un baño o un vidrio roto, y cómo se entera el director.',
 m:{t:'Pedidos de mantenimiento',u:'mantenimiento',b:'Nuevo pedido',k:[['23','abiertos'],['4','urgentes'],['92%','dentro de plazo']],c:['Pedido','Lugar','Prioridad','Estado'],r:[['Vidrio roto','Aula 2.º A','Alta','b:En curso'],['Fuga en baño','Planta baja','Urgente','a:Asignado'],['Luminaria','Pasillo 2','Media','g:Resuelto'],['Revisión de extintores','Todo el colegio','Preventivo','b:Programado']]}},
{id:'tienda',a:'campus',n:'Tienda escolar',
 f:'Venta de uniformes, libros y materiales con pedido, pago y entrega.',
 p:'Venta de uniformes en efectivo, sin control de tallas ni de entregas.',
 s:['Catálogo con precios aprobados','Pedido desde la app','Pago con QR o cargo al estado de cuenta','Entregas y devoluciones registradas'],
 u:['Familias','Administración'],x:['pagos','inventario','portal'],
 note:'Es un ingreso adicional para el colegio y una comodidad para la familia.',
 m:{t:'Pedidos de la tienda',u:'tienda',b:'Nuevo producto',k:[['74','pedidos'],['Bs 21.300','vendido'],['9','por entregar']],c:['Pedido','Familia','Monto','Estado'],r:[['Buzo deportivo T10','Guzmán Ortiz','Bs 280','g:Entregado'],['Kit de útiles 1.º','Paz Limachi','Bs 350','b:Por entregar'],['Libro de inglés 3','Flores Arce','Bs 190','g:Pagado'],['Chompa T12','Aliaga Soto','Bs 160','a:Por pagar']]}},

/* ---------------- COMUNIDAD ---------------- */
{id:'portal',a:'comunidad',n:'App para padres',
 f:'Todo lo de cada hijo en el celular: estado de cuenta, pago, notas, asistencia, comunicados y trámites.',
 p:'Los padres llaman o van a secretaría para cualquier consulta.',
 s:['Estado de cuenta y pago con QR','Notas, boletines y asistencia','Comunicados, autorizaciones y encuestas','Trámites y certificados sin ir al colegio'],
 u:['Familias','Estudiantes'],x:['pensiones','pagos','notas','comunicacion','tramites'],
 note:'Enséñala en tu propio celular. Es lo que más convence a un director, porque es lo que van a ver sus padres de familia.',
 m:'phone'},
{id:'comunicacion',a:'comunidad',n:'Comunicados y circulares',
 f:'Envía comunicados a quien corresponde y muestra quién los leyó.',
 p:'Circulares por WhatsApp sin saber quién las leyó, y autorizaciones en papel que no vuelven.',
 s:['Comunicados por curso, nivel, sede o grupo','Confirmación de lectura','Autorizaciones y encuestas con respuesta','Envío por app, correo, SMS o WhatsApp según la preferencia de la familia'],
 u:['Dirección','Docentes','Secretaría','Familias'],x:['portal','convivencia','extracurriculares'],
 note:'La pregunta: “¿cuántas familias leyeron la última circular?”. Hoy no lo saben; aquí es un porcentaje.',
 m:{t:'Comunicados de septiembre',u:'comunicados',b:'Nuevo comunicado',k:[['24','enviados'],['88%','lectura promedio'],['418','autorizaciones']],c:['Comunicado','Destinatarios','Lectura','Estado'],r:[['Salida al museo','3.º secundaria','92%','g:Enviado'],['Cambio de horario','Toda la sede','81%','g:Enviado'],['Encuesta de comedor','Primaria','64%','b:Abierta'],['Reunión de padres','4.º B','—','a:Programado']]}},
{id:'tramites',a:'comunidad',n:'Certificados y trámites',
 f:'Los padres piden certificados y constancias, y el sistema revisa los requisitos antes de emitirlos.',
 p:'Filas en secretaría, certificados hechos en Word y requisitos revisados a mano.',
 s:['Solicitud desde la app','Revisión automática de requisitos (pago, documentos, notas)','Documentos con plantilla oficial y firma','Seguimiento del trámite por la familia'],
 u:['Secretaría','Familias'],x:['notas','pensiones','portal','documentos'],
 note:'Ejemplo potente: el sistema no emite la libreta si hay deuda pendiente, sin que secretaría tenga que revisar nada.',
 m:{t:'Trámites',u:'tramites',b:'Emitir',k:[['37','solicitudes'],['29','emitidos'],['3','observados']],c:['Trámite','Solicitante','Requisito','Estado'],r:[['Certificado de estudios','Familia Guzmán','Pago al día','g:Emitido'],['Constancia de inscripción','Familia Paz','—','g:Emitido'],['Libreta 2025','Familia Rojas','Deuda pendiente','r:Observado'],['Certificado de conducta','Familia Salazar','—','b:En firma']]}},
{id:'crm',a:'comunidad',n:'Marketing y postulantes',
 f:'Sigue a cada familia interesada desde el primer contacto hasta que postula.',
 p:'Interesados que preguntan por redes sociales o WhatsApp y a quienes nadie les hace seguimiento.',
 s:['Registro de interesados con su origen','Visitas y entrevistas agendadas','Seguimiento por etapa','Qué campañas traen más matrículas'],
 u:['Dirección','Secretaría'],x:['admisiones','comunicacion'],
 note:'Para colegios que compiten por matrícula: saber qué campaña trae familias que realmente se inscriben.',
 m:{t:'Embudo de admisión 2027',u:'marketing',b:'Nuevo interesado',k:[['486','interesados'],['214','postularon'],['132','matriculados']],c:['Origen','Interesados','Postularon','Estado'],r:[['Redes sociales','212','78','b:Activo'],['Recomendación','96','64','g:Mejor origen'],['Feria educativa','88','41','b:Activo'],['Sitio web','90','31','a:Revisar']]}},
{id:'legal',a:'comunidad',n:'Contratos y convenios',
 f:'Contratos, convenios y obligaciones legales del colegio, con sus vencimientos.',
 p:'Contratos guardados en carpetas y renovaciones que se pasan de fecha.',
 s:['Registro de contratos y convenios','Obligaciones y vencimientos con aviso','Versiones y firma','Cumplimiento con respaldo'],
 u:['Dirección','Administración'],x:['compras','becas','documentos'],
 note:'Útil para el promotor o el directorio del colegio.',
 m:{t:'Contratos vigentes',u:'contratos',b:'Nuevo contrato',k:[['42','contratos'],['5','vencen en 60 días'],['2','por firmar']],c:['Contrato','Contraparte','Vence','Estado'],r:[['Servicio de transporte','Transportes Andinos','31/12','g:Vigente'],['Alquiler de cancha','Club deportivo','15/11','a:Por vencer'],['Convenio de becas','Empresa Andina','28/02','g:Vigente'],['Seguro escolar','Aseguradora','—','b:Por firmar']]}},

/* ---------------- DIRECCIÓN ---------------- */
{id:'analitica',a:'direccion',n:'Tablero de dirección',
 f:'Los números clave del colegio, por sede, actualizados solos.',
 p:'Para saber cómo va el colegio hay que pedir informes a cada área y esperar.',
 s:['Matrícula, cobranza, asistencia y rendimiento en una pantalla','Comparación entre sedes y gestiones','Alertas cuando un indicador se sale de lo esperado','Informes para directorio'],
 u:['Dirección'],x:['notas','pensiones','asistencia','riesgo'],
 note:'Muéstralo al principio y al final. Es la foto del colegio que el director no tiene hoy.',
 m:{t:'Tablero de dirección',u:'direccion',b:'Informe para directorio',k:[['1.284','estudiantes'],['91,4%','cobranza'],['95,2%','asistencia']],c:['Sede','Estudiantes','Cobranza','Estado'],r:[['Calacoto','712','94%','g:En meta'],['Miraflores','398','86%','r:Bajo la meta'],['El Alto','174','92%','g:En meta'],['Total','1.284','91%','b:Consolidado']]}},
{id:'riesgo',a:'direccion',n:'Alertas de riesgo académico',
 f:'Identifica a los estudiantes en riesgo de reprobar o abandonar, y explica por qué.',
 p:'Los estudiantes en riesgo se detectan cuando ya reprobaron.',
 s:['Riesgo calculado con asistencia, notas y conducta','Cada alerta explica qué la originó','Prioridades para orientación y tutores','Seguimiento de lo que se hizo con cada alerta'],
 u:['Dirección','Orientación','Coordinación'],x:['asistencia','notas','bienestar'],
 note:'Deja claro que el sistema sugiere y una persona decide. Nadie queda etiquetado automáticamente.',
 m:{t:'Estudiantes en riesgo',u:'riesgo',b:'Asignar a orientación',k:[['17','alertas'],['5','nuevas'],['11','con plan']],c:['Estudiante','Curso','Motivo','Estado'],r:[['Choque Rivera, Mateo','3.º B','Faltas y notas','r:Alto'],['Vargas Loza, Sofía','3.º B','Notas','a:Medio'],['Aliaga Soto, Mía','1.º A','Faltas','a:Medio'],['Ortiz Mendoza, Leo','5.º C','Conducta','b:Seguimiento']]}},
{id:'asistente',a:'direccion',n:'Asistente con inteligencia artificial',
 f:'Responde preguntas de padres, docentes y personal con la información del colegio, citando de dónde la saca.',
 p:'Secretaría responde las mismas preguntas todos los días, una por una.',
 s:['Un asistente para familias, estudiantes, docentes y administración','Respuestas basadas en reglamentos y datos del colegio, con la fuente','Prepara borradores de comunicados y trámites','Nada se envía sin la aprobación de una persona'],
 u:['Familias','Docentes','Secretaría','Dirección'],x:['portal','comunicacion','tramites'],
 note:'Ejemplo: un padre pregunta “¿cuándo es la reunión?” y el asistente responde con la circular. Siempre con fuente y sin inventar.',
 q:['¿La IA ve datos privados?','Solo lo que el perfil de cada usuario puede ver, con consentimiento y bajo reglas que define el colegio. Todo queda registrado.'],
 m:{t:'Asistente, consultas de la semana',u:'asistente',b:'Ver conversaciones',k:[['1.312','consultas'],['94%','resueltas'],['41','derivadas a personas']],c:['Pregunta','Perfil','Fuente','Estado'],r:[['¿Cuándo es la reunión de padres?','Familia','Circular 24/09','g:Resuelta'],['¿Cuánto debo de pensión?','Familia','Estado de cuenta','g:Resuelta'],['Redactar aviso de salida','Docente','Plantilla','a:Borrador por aprobar'],['Reclamo por una nota','Familia','—','b:Derivada']]}},
{id:'calidad',a:'direccion',n:'Calidad y acreditación',
 f:'Organiza la autoevaluación, las evidencias y los planes de mejora del colegio.',
 p:'La acreditación se prepara con carpetas y evidencias reunidas a última hora.',
 s:['Criterios e indicadores de calidad','Evidencias vinculadas a cada criterio','Hallazgos y planes de mejora','Proyectos institucionales con seguimiento'],
 u:['Dirección','Coordinación'],x:['analitica','legal','documentos'],
 note:'Para colegios que buscan una acreditación o certificación de calidad.',
 m:{t:'Autoevaluación 2026',u:'calidad',b:'Subir evidencia',k:[['48','criterios'],['71%','con evidencia'],['9','acciones de mejora']],c:['Dimensión','Criterios','Evidencia','Estado'],r:[['Gestión pedagógica','14','86%','g:Avanzado'],['Convivencia','8','62%','a:En proceso'],['Infraestructura','10','70%','b:En proceso'],['Gestión administrativa','16','68%','b:En proceso']]}},
{id:'personal',a:'direccion',n:'Personal y docentes',
 f:'Perfiles del personal, disponibilidad y asignaciones, conectado con recursos humanos.',
 p:'La información de los docentes está en RRHH y la académica en otro lado.',
 s:['Perfil de cada persona y su rol','Disponibilidad y carga horaria','Asignaciones por sede, curso y área','Sincronización con el sistema de RRHH'],
 u:['Dirección','Coordinación','Administración'],x:['horarios','docente'],
 note:'Aclara que no es un sistema de planillas de sueldos: se conecta con el que ya usa RRHH.',
 m:{t:'Personal activo',u:'personal',b:'Asignar',k:[['142','personas'],['96','docentes'],['4','sin asignar']],c:['Persona','Rol','Carga','Estado'],r:[['Quispe, Luis','Docente','32 h','g:Asignado'],['Mamani, Rosa','Docente','28 h','g:Asignado'],['Torrez, Ana','Psicopedagoga','40 h','g:Asignada'],['Vaca, Pedro','Docente','12 h','a:Carga baja']]}},

/* ---------------- BASE ---------------- */
{id:'personas',a:'base',n:'Estudiantes y familias',
 f:'Cada persona existe una sola vez, con todos sus vínculos: hijos, padres, apoderados y responsable de pago.',
 p:'El mismo padre aparece tres veces, con teléfonos distintos en cada planilla.',
 s:['Un solo registro por persona','Vínculos familiares y apoderados','Responsable económico de cada estudiante','Datos de contacto y documentos al día'],
 u:['Secretaría','Administración'],x:['admisiones','pensiones','portal'],
 note:'Es la base de todo. Si cambia el teléfono de un padre, cambia en todo el sistema a la vez.',
 m:{t:'Familia Choque Rivera',u:'familias/choque-rivera',b:'Editar',k:[['2','hijos'],['3','adultos vinculados'],['1','responsable de pago']],c:['Persona','Vínculo','Rol','Estado'],r:[['Carla Rivera','Madre','Responsable económica','g:Activa'],['Marco Choque','Padre','Apoderado','g:Activo'],['Mateo Choque Rivera','Hijo','3.º de secundaria B','g:Matriculado'],['Valeria Choque Rivera','Hija','5.º de primaria','g:Matriculada']]}},
{id:'estructura',a:'base',n:'Sedes, niveles y cursos',
 f:'La estructura del colegio: sedes, turnos, niveles, cursos y paralelos.',
 p:'Cada sede funciona como un colegio aparte, con su propio Excel.',
 s:['Una institución con varias sedes','Niveles, grados, paralelos y turnos','Gestiones escolares','Base para los permisos y los reportes'],
 u:['Dirección'],x:['analitica','horarios','permisos'],
 note:'Si el colegio tiene varias sedes, este es el argumento: una sola institución, con reportes por sede o consolidados.',
 m:{t:'Estructura institucional',u:'estructura',b:'Nueva sede',k:[['3','sedes'],['48','paralelos'],['2','turnos']],c:['Sede','Niveles','Paralelos','Estado'],r:[['Calacoto','Inicial a secundaria','26','g:Activa'],['Miraflores','Primaria y secundaria','15','g:Activa'],['El Alto','Inicial y primaria','7','g:Activa'],['Achumani','Inicial','—','b:Proyecto 2027']]}},
{id:'documentos',a:'base',n:'Documentos y firma digital',
 f:'Los documentos del colegio guardados en un solo lugar, con versiones y firma dentro del sistema.',
 p:'Documentos en carpetas físicas o perdidos en correos.',
 s:['Documentos por estudiante, familia o área','Versiones y acceso controlado','Firma de contratos, compromisos y actas','Respaldo verificable'],
 u:['Secretaría','Administración','Dirección'],x:['tramites','cobranza','legal'],
 note:'Los compromisos de pago y los contratos de servicio se firman desde la app. Se acaba el papel que no vuelve.',
 m:{t:'Documentos recientes',u:'documentos',b:'Subir',k:[['18.240','documentos'],['312','firmados este mes'],['6','por firmar']],c:['Documento','Relacionado con','Tipo','Estado'],r:[['Contrato de servicios 2026','Familia Guzmán','Contrato','g:Firmado'],['Compromiso de pago','Familia Rojas','Compromiso','a:Por firmar'],['Acta de consejo','Dirección','Acta','g:Firmado'],['Certificado de nacimiento','Rojas Arce, Valentina','Respaldo','g:Verificado']]}},
{id:'aprobaciones',a:'base',n:'Aprobaciones y pendientes',
 f:'Las solicitudes pasan por quien corresponde, con plazos y responsable visibles.',
 p:'Aprobaciones por WhatsApp o de palabra, sin registro de quién dijo qué.',
 s:['Bandeja de pendientes por persona','Aprobaciones de uno o varios niveles','Plazos y aviso de atraso','Historial de cada decisión'],
 u:['Dirección','Administración','Coordinación'],x:['becas','compras','notas'],
 note:'Muestra la bandeja del director: todo lo que espera su decisión, en un solo lugar.',
 m:{t:'Mi bandeja',u:'pendientes',b:'Aprobar seleccionados',k:[['8','pendientes'],['2','vencen hoy'],['41','resueltos este mes']],c:['Solicitud','Módulo','Plazo','Estado'],r:[['Beca solidaria, familia Paz','Becas','Hoy','a:Pendiente'],['Compra de pintura','Compras','Mañana','a:Pendiente'],['Reabrir notas 4.º A','Notas','Hoy','r:Urgente'],['Baja de impresora','Activos','Viernes','b:En revisión']]}},
{id:'reglas',a:'base',n:'Configuración y reglas',
 f:'El colegio define sus propias reglas sin programar: aranceles, requisitos, bloqueos y alertas.',
 p:'Cada regla depende de que alguien la recuerde y la aplique.',
 s:['Parámetros por sede, nivel y gestión','Reglas como “sin deuda no se emite libreta”','Módulos que se activan por etapas','Cambios aprobados y registrados'],
 u:['Dirección','Administración'],x:['tramites','becas','pensiones'],
 note:'El argumento: el sistema se adapta al colegio, no el colegio al sistema.',
 m:{t:'Reglas activas',u:'configuracion/reglas',b:'Nueva regla',k:[['34','reglas'],['6','módulos activos'],['2','cambios por aprobar']],c:['Regla','Aplica a','Desde','Estado'],r:[['Sin deuda no se emite libreta','Todas las sedes','2026','g:Activa'],['Descuento hermanos 15%','Todas las sedes','2026','g:Activa'],['3 faltas seguidas: aviso a orientación','Secundaria','2026','g:Activa'],['Mora de 60 días: compromiso obligatorio','Calacoto','Oct 2026','a:Por aprobar']]}},
{id:'permisos',a:'base',n:'Permisos, historial y privacidad',
 f:'Cada persona ve solo lo que le corresponde, y cada cambio queda registrado.',
 p:'Todos ven todo en la planilla compartida, y nadie sabe quién cambió una nota.',
 s:['Permisos por rol, sede y curso','Historial de quién cambió qué y cuándo','Consentimientos de la familia registrados','Datos sensibles protegidos'],
 u:['Dirección'],x:['notas','salud','bienestar'],
 note:'Cierra con esto: tranquilidad legal para el colegio. Si alguien pregunta quién cambió una nota, hay respuesta.',
 m:{t:'Historial de cambios',u:'auditoria',b:'Exportar',k:[['100%','acciones registradas'],['12','roles'],['3','accesos bloqueados']],c:['Acción','Usuario','Fecha','Estado'],r:[['Cambio de nota, Matemática','Prof. Quispe','22/09 16:04','g:Aprobado'],['Reapertura de trimestre','Coordinación','21/09 09:12','g:Aprobado'],['Consulta de ficha médica','Caja','20/09 11:30','r:Bloqueado'],['Descuento aplicado','Administración','19/09 10:05','g:Registrado']]}}
];
